
INSERT INTO buildings(building_name, building_image) VALUES ('Murad buildings', 'murad-buildings.png');
INSERT INTO buildings(building_name, building_image) VALUES ('Golden House', 'golden-house.png');
INSERT INTO buildings(building_name, building_image) VALUES ('Dreamcity', 'dreamcity.png');
INSERT INTO buildings(building_name, building_image) VALUES ('Dream House', 'dream-house.png');


INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Nest One', 'Tashkent, O`zbekiston', 'nest-one.jpg', 1);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Kislorod', 'Tashkent, Oybek', 'kislorod.jpeg', 1);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Green city', 'Tashkent, Bunyodkor', 'green-city.jpeg', 1);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Assalom sohil', 'Tashkent, Farg`ona', 'assalom-sohil.jpg', 2);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Infinity', 'Tashkent, Istiqbol', 'infinity.jpeg', 2);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Greenwich', 'Tashkent, Yangi zamon', 'greenwich.jpeg', 2);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Boulivard', 'Tashkent, Furqat', 'boulivard.jpg', 3);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Gardens', 'Tashkent, Navoiy', 'gardens.jpg', 3);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Seoul Mun', 'Tashkent, Bobur', 'seoul-mun.png', 3);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Bodomzor', 'Tashkent, Bodomzor', 'bodomzor.jpg', 4);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Xon Saroy', 'Tashkent, Kichik beshagach', 'xon-saroy.jpeg', 4);
INSERT INTO complexes(complex_name, complex_address, complex_image, building_id) VALUES ('Milano', 'Tashkent, Mustaqillik', 'milano.jpeg', 4);


INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 40, 7900000, 1);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 60, 7900000, 1);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 80, 7900000, 1);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 100, 7900000, 1);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 120, 7900000, 1);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 50, 4900000, 2);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 70, 4900000, 2);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 90, 4900000, 2);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 110, 4900000, 2);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 130, 4900000, 2);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 60, 3900000, 3);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 80, 3900000, 3);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 100, 3900000, 3);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 120, 3900000, 3);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 140, 3900000, 3);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 70, 5900000, 4);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 90, 5900000, 4);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 110, 5900000, 4);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 130, 5900000, 4);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 150, 5900000, 4);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 80, 7900000, 5);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 100, 7900000, 5);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 120, 7900000, 5);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 140, 7900000, 5);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 160, 7900000, 5);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 90, 4900000, 6);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 110, 4900000, 6);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 130, 4900000, 6);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 150, 4900000, 6);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 170, 4900000, 6);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 100, 3900000, 7);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 120, 3900000, 7);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 140, 3900000, 7);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 160, 3900000, 7);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 180, 3900000, 7);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 110, 5900000, 8);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 130, 5900000, 8);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 150, 5900000, 8);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 170, 5900000, 8);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 190, 5900000, 8);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 120, 7900000, 9);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 140, 7900000, 9);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 160, 7900000, 9);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 180, 7900000, 9);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 200, 7900000, 9);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 130, 4900000, 10);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 150, 4900000, 10);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 170, 4900000, 10);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 190, 4900000, 10);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 210, 4900000, 10);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 140, 3900000, 11);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 160, 3900000, 11);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 180, 3900000, 11);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 200, 3900000, 11);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 220, 3900000, 11);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (1, 150, 5900000, 12);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (2, 170, 5900000, 12);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (3, 190, 5900000, 12);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (4, 210, 5900000, 12);
INSERT INTO rooms(room_amount, room_capacity, room_capacity_price, complex_id) VALUES (5, 230, 5900000, 12);


INSERT INTO banks(bank_name, bank_image, bank_max_amount, bank_credit_deadline, bank_starter_amount) VALUES ('Agrobank', 'agrobank.png', 500000000, 30, 20);
INSERT INTO banks(bank_name, bank_image, bank_max_amount, bank_credit_deadline, bank_starter_amount) VALUES ('Hamkorbank', 'hamkorbank.png', 500000000, 20, 25);
INSERT INTO banks(bank_name, bank_image, bank_max_amount, bank_credit_deadline, bank_starter_amount) VALUES ('Anorbank', 'anorbank.png', 600000000, 10, 28);
INSERT INTO banks(bank_name, bank_image, bank_max_amount, bank_credit_deadline, bank_starter_amount) VALUES ('TBC', 'tbc.png', 700000000, 5, 30);
INSERT INTO banks(bank_name, bank_image, bank_max_amount, bank_credit_deadline, bank_starter_amount) VALUES ('Kapitalbank', 'kapitalbank.jpg', 1000000000, 20, 20);
INSERT INTO banks(bank_name, bank_image, bank_max_amount, bank_credit_deadline, bank_starter_amount) VALUES ('NBU', 'milliybank.png', 800000000, 10, 15);
INSERT INTO banks(bank_name, bank_image, bank_max_amount, bank_credit_deadline, bank_starter_amount) VALUES ('Ipak Yo`li Bank', 'ipakyoli.png', 1200000000, 30, 20);